#!/bin/sh
printf '%s\n' "Welcome to git-server-docker!"
printf '%s\n' ""
printf '%s\n' "You've authenticated successfully, but this"
printf '%s\n' "git server does not provide interactive shell access."
exit 128
